### ISSUE TITLE
Python2 may be an unsafe alias?

### ISSUE THREAD

**Issue by justingarrick** [andyt530/py-az2tf#1]
Thanks for the badass tool!

I was able to easily work around this by creating an alias, but just a note that on my machine, `python2` doesn't resolve to anything, while `python` resolves to v2.7 and `python3` resolves to v3.7.3.  Not sure it is safe to assume python2 exists with the variety of ways python could be installed/configured on MacOS (Homebrew, Apple Python, etc.).

https://github.com/andyt530/py-az2tf/blob/4dd204c263cb59a186c69090ad348dddb24caeea/az2tfpy.sh#L84

**Comment by andyt530** [comment]
Hi - Does "python2.7" work on your system ?

**Comment by justingarrick** [comment]
Sure does.  I think it might make sense to do some sort of check in `az2tfpy.sh` w/ `ls /usr/bin/python2*`, then use the result before invoking python.  Alternatively, I'm sure there is some sort of FOSS solution for this already; my py-fu is pretty weak.
