### ISSUE TITLE
ImportError: No module named requests

### ISSUE THREAD

**Issue by Nithinraot** [andyt530/py-az2tf#12]
I tried to run this tool but getting below error.

nithin@Azure:~/py-az2tf$ ./az2tf.sh -s xxxxxxxxxxxxxxxxxxxxxxxxxxxxx-v yes

Subscription ID = xxxxxxxxxxxxxxxxxxxxxxxx
Azure Resource Group Filter =
Terraform Resource Type Filter =
Get Subscription Policies & RBAC = no
Extract Key Vault Secrets to .tf files (insecure) = no
Fast Forward = no
Validate Only = yes
Debug = no

python2.7 ../../scripts/az2tf.py -s XXXXXXXXXXXXXXXXXXXX  2>&1 | tee -a import.log
Traceback (most recent call last):
  File "../../scripts/az2tf.py", line 4, in <module>
    import requests
ImportError: No module named requests
ImportError: No module named requests
Error in az2tf.py

**Comment by andyt530** [comment]
Hi,

Try:

sudo pip install requests

**Comment by Nithinraot** [comment]
Thanks for your immediate revert. I tried but not of much help.
I am new to this so apologies on basic queries.

nithin@Azure:~/py-az2tf$ ./az2tf.sh -s asdfsadfsafdsafdasfd 7 -v yes

Subscription ID = asdfasdfsadfsadf
Azure Resource Group Filter =
Terraform Resource Type Filter =
Get Subscription Policies & RBAC = no
Extract Key Vault Secrets to .tf files (insecure) = no
Fast Forward = no
Validate Only = yes
Debug = no

python2.7 ../../scripts/az2tf.py -s asdfasdfsadfasfdsdf 2>&1 | tee -a import.log
Traceback (most recent call last):
  File "../../scripts/az2tf.py", line 4, in <module>
    import requests
ImportError: No module named requests
ImportError: No module named requests
Error in az2tf.py
nithin@Azure:~/py-az2tf$ pip install requests
Requirement already satisfied: requests in /usr/local/lib/python3.5/dist-packages (2.22.0)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python3.5/dist-packages (from requests) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.5/dist-packages (from requests) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.5/dist-packages (from requests) (1.25.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.5/dist-packages (from requests) (2019.3.9)

**Comment by andyt530** [comment]
hi - looks like you pip installed to your python 3.x environment - rather than python2 environment

**Comment by andyt530** [comment]
Try - sudo pip2 install requests
