### ISSUE TITLE
no *state*.sh

### ISSUE THREAD

**Issue by zoemac11** [andyt530/py-az2tf#13]
chmod: cannot access '*state*.sh': No such file or directory                     state cleaned                                                                    ls: cannot access '**stateimp.sh': No such file or directory                     imports completed                                                                Terraform fmt ...                                                                azure.tf                                                                         Terraform Plan ...                                                               Refreshing Terraform state in-memory prior to plan...                            The refreshed state will be used to calculate this plan, but will not be         persisted to local or remote state storage.
--

**Comment by andyt530** [comment]
Can you give me a little more of the output - before and after.

**Comment by zoemac11** [comment]
terraform validate                                                               Success! The configuration is valid.                                                                                                                              chmod: cannot access '*state*.sh': No such file or directory                     state cleaned                                                                    ls: cannot access '**stateimp.sh': No such file or directory                     imports completed                                                                Terraform fmt ...                                                                azure.tf                                                                         Terraform Plan ...                                                               Refreshing Terraform state in-memory prior to plan...                            The refreshed state will be used to calculate this plan, but will not be         persisted to local or remote state storage.                                                                                                                                                                                                        ------------------------------------------------------------------------                                                                                          No changes. Infrastructure is up-to-date.
--

**Comment by andyt530** [comment]
And can you share:

1. The actually command line you are running   ./az2tf.sh ......
2. The output between that command and the terraform validate Success!
3. are there any *.tf files being generated in the sub-directory  generated/tf.<your sub id> ?

Thanks

**Comment by zoemac11** [comment]
Its generating file but its empty, only contains terraform and provider 'azurerm'. Ive removed my subscription ID 

./az2tf.sh -s <subscriptionID>

Subscription ID = <subscriptionID>
Azure Resource Group Filter =
Terraform Resource Type Filter =
Get Subscription Policies & RBAC = no
Extract Key Vault Secrets to .tf files (insecure) = no
Fast Forward = no
Validate Only = no
Debug = no

python2.7 ../../scripts/az2tf.py -s <subscriptionID> 2>&1 | tee -a import.log
./az2tf.sh: line 123: python2.7: command not found
terraform init

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "azurerm" (terraform-providers/azurerm) 1.31.0...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
terraform validate
Success! The configuration is valid.

**Comment by andyt530** [comment]
Ah - here's the problem:

python2.7 ../../scripts/az2tf.py -s 2>&1 | tee -a import.log
./az2tf.sh: line 123: python2.7: command not found

It couldn't find python v 2.7 on your system - so the main bulk of the code that generates the terraform didn't run

I'll code in a test to drop out with a better error......

In the meantime - unless you can run "python2.7"  - or alias that to python v2 on your system this isn't going to work for you....

**Comment by zoemac11** [comment]
If i run python it works fine and shows that its version 2.7

$ python --version                                                               Python 2.7.16
--

**Comment by andyt530** [comment]
Hi,

There are many many ways python can get installed and be available on the command line.
I'll have to work some more logic in to cover all these cases.

In the meantime you should be able to work-around simple by changing that "python2.7"  to "python" in the az2tf.sh file (line 91)

If you have the time could you please give that a try and let me know how you get on ?

Thanks

**Comment by zoemac11** [comment]
Thanks! I'm now getting the following errors


python ../../scripts/az2tf.py -s 7e42623b-2051-4ab2-a66b-36b5866ac99b 2>&1 \| tee                      -a import.log                                                                                       Get Access Token from CLI                                                                            Subscription: 7e42623b-2051-4ab2-a66b-36b5866ac99b                                                   Traceback (most recent call last):                                                                     File "../../scripts/az2tf.py", line 200, in                                                    r = requests.get(url, headers=headers, params=params)                                              File "C:\Users\AppData\Roaming\Python\Python27\site-packages\reques                     ts\api.py", line 75, in get                                                                              return request('get', url, params=params, **kwargs)                                                File "C:\Users\AppData\Roaming\Python\Python27\site-packages\reques                     ts\api.py", line 60, in request                                                                          return session.request(method=method, url=url, **kwargs)                                           File "C:\Users\AppData\Roaming\Python\Python27\site-packages\reques                     ts\sessions.py", line 519, in request                                                                    prep = self.prepare_request(req)                                                                   File "C:\Users\AppData\Roaming\Python\Python27\site-packages\reques                     ts\sessions.py", line 462, in prepare_request                                                            hooks=merge_hooks(request.hooks, self.hooks),                                                      File "C:\Users\AppData\Roaming\Python\Python27\site-packages\reques                     ts\models.py", line 314, in prepare                                                                      self.prepare_headers(headers)                                                                      File "C:\Users\AppData\Roaming\Python\Python27\site-packages\reques                     ts\models.py", line 448, in prepare_headers                                                              check_header_validity(header)                                                                      File "C:\Users\AppData\Roaming\Python\Python27\site-packages\reques                     ts\utils.py", line 942, in check_header_validity                                                         raise InvalidHeader("Invalid return character or leading space in header: %s                     " % name)                                                                                            requests.exceptions.InvalidHeader: Invalid return character or leading space in                      header: Authorization                                                                                terraform init
--

**Comment by andyt530** [comment]
Hi,

Two things to try:

1. sudo pip install requests
2. have you logged in to azure via the CLI ?

Thanks

**Comment by zoemac11** [comment]
The issue is with the request module. Couldnt get it to work but thanks

**Comment by andyt530** [comment]
When you fix that - it should be ok

**Comment by peter-mogaka** [comment]
having the same issue. I have python 3 and installed pip requests and pip adal.
@zoemac11 How did you solve this error?
@andyt530 can't find line 91 on the az2tf.sh file

![2021-04-28 13_17_48-az2tf sh - Visual Studio Code](https://user-images.githubusercontent.com/78694283/116395307-3ec02180-a824-11eb-9280-b9329a494ca2.png)
