### ISSUE TITLE
Problem with ExpressRoute Private Peering

### ISSUE THREAD

**Issue by rouxton** [andyt530/py-az2tf#15]
Hello,

The script hangs on a type conversion error at several steps, I'm summing it up here : 

azurerm_virtual_network_gateway_connection.py, line 127 & 128 -> TypeError: cannot concatenate 'str' and 'int' objects
azurerm_express_route_circuit_peering.py, line 78 -> TypeError: cannot concatenate 'str' and 'list' objects

Each time solved by using str function in the print statement (might not be the solution but in order to move one step further it helps).

Another one easily fixed in the latter, line 74, it should be :
if pt == "MicrosoftPeering" or pt == "AzurePrivatePeering":
instead of 
if pt == "MicrosoftPeering" or "pt" == "AzurePrivatePeering":

After that, it fails validation :

Error: Argument or block definition required

  on azurerm_express_route_circuit_peering.network-prod-rg__AzurePrivatePeering.tf line 13, in resource "azurerm_express_route_circuit_peering" "network-prod-rg__AzurePrivatePeering":

An argument or block definition is required here.

The tf file (real info obfuscated obviously):

resource azurerm_express_route_circuit_peering network-prod-rg__AzurePrivatePeering {
	 resource_group_name = "some-rg"
	 peering_type = "AzurePrivatePeering"
	 express_route_circuit_name = "some-circuit"
	 primary_peer_address_prefix = "xxxxxx/30"
	 secondary_peer_address_prefix = "xxxxxx/30"
	 vlan_id = "xx"
	 peer_asn = "xxxx"
	 microsoft_peering_config {
		 advertised_public_prefixes =  "[]" 
	 }

Maybe more a terraform issue, I haven't been able to find a reference for AzurePrivatePeering.

Tx

**Comment by andyt530** [comment]
Thanks - committed in those str() changes 

Researching the AzurePrivatePeering issue .....

**Comment by andyt530** [comment]
Hi - committed what hopefully is a fix - please give it a try and let me know how you get on.

**Comment by rouxton** [comment]
Thanks Andy, 

Unfortunately, still the peering issue but I think it's a TF issue. I'll check a little bit more and I'll open a bug with Terraform if necessary
