### ISSUE TITLE
Error unicode when running az2tf.sh -v yes 

### ISSUE THREAD

**Issue by tazd007** [andyt530/py-az2tf#18]
HI 
When running   az2tf.sh -v yes  hitting the following error 

# azurerm_resource_group 16
# azurerm_management_lock 13
# azurerm_user_assigned_identity 0
# azurerm_availability_set 0
# azurerm_route_table 1
# azurerm_application_security_group 0
# azurerm_network_security_group 8
# azurerm_virtual_network 4
# azurerm_subnet 4
# azurerm_virtual_network_peering 4
# azurerm_key_vault 5
# azurerm_managed_disk 46
Traceback (most recent call last):
  File "../../scripts/az2tf.py", line 298, in <module>
    azurerm_managed_disk.azurerm_managed_disk(crf,cde,crg,headers,requests,sub,json,az2tfmess)
  File "/home/dooret/py-az2tf/scripts/azurerm_managed_disk.py", line 135, in azurerm_managed_disk
    fr.write('\t "' + key + '"="' + tval + '"\n')
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 31: ordinal not in range(128)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 31: ordinal not in range(128)
Error in az2tf.py

**Comment by tazd007** [comment]
Hi 
Replacing 
fr.write('\t "' + key + '"="' + tval + '"\n')
with 
fr.write(('\t "' + key + '"="' + tval + '"\n').encode('utf-8'))
in the following files allowed the -v to complete without error 
/scripts/azurerm_managed_disk.py
/scripts/azurerm_public_ip.py
/scripts/azurerm_network_interface.py
/scripts/azurerm_virtual_machine.py
regards 
Tony

**Comment by andyt530** [comment]
Thanks - pushed that fix into everything.
