### ISSUE TITLE
Consider supporting Terraform 12.x

### ISSUE THREAD

**Issue by oising** [andyt530/py-az2tf#2]
Great job -- I was not expecting to find anyone masochistic enough to start on this, but lo and behold, there you were :)

In my excitement to race ahead, I overlooked your version 11.11 requirement (latest is 11.14 as of this writing, I'll assume you just mean 11.x) and ran it with 12.x installed. It actually worked until it got to validate, and the only thing it complained about were the tags I'd assigned to my resources:
```
Error: Unsupported block type

  on azurerm_resource_group__ccma-qa-resources.tf line 4, in resource "azurerm_resource_group" "ccma-qa-resources":
   4:   tags {

Blocks of type "tags" are not expected here. Did you mean to define argument
"tags"? If so, use the equals sign to assign it a value.
```
This doesn't seem like a huge issue - any chance of realigning the rebirth of this project in pyhton with a  v12 dependency so as to not get left in the sunset? If not, that's okay - but perhaps you could direct me as to where I should look to hack this in myself to emit v12 compatible tag schema?

**Comment by andyt530** [comment]
Hi,
Yes 12.x version is in the works.

**Comment by andyt530** [comment]
Hi - There you go - v0.12 done
