### ISSUE TITLE
TypeError: cannot concatenate 'str' and 'NoneType' objects Error in az2tf.py

### ISSUE THREAD

**Issue by MDavies-AA** [andyt530/py-az2tf#23]
# azurerm_resource_group 32
# azurerm_management_lock 4
# azurerm_user_assigned_identity 0
# azurerm_availability_set 6
# azurerm_route_table 1
# azurerm_application_security_group 0
# azurerm_network_security_group 16
# azurerm_virtual_network 5
# azurerm_subnet 5
# azurerm_virtual_network_peering 5
# azurerm_key_vault 2
# azurerm_managed_disk 61
# azurerm_storage_account 25
# azurerm_public_ip 10
# azurerm_traffic_manager_profile 0
# azurerm_traffic_manager_endpoint 0
# azurerm_network_interface 30
# azurerm_dns_zone 0
# azurerm_lb 3
# azurerm_lb_nat_rule 3
# azurerm_lb_nat_pool 3
# azurerm_lb_backend_address_pool 3
# azurerm_lb_probe 3
# azurerm_lb_rule 3
# azurerm_application_gateway 2
Traceback (most recent call last):
  File "../../scripts/az2tf.py", line 333, in <module>
    azurerm_application_gateway.azurerm_application_gateway(crf,cde,crg,headers,requests,sub,json,az2tfmess)
  File "/home/platforms/az2tf/py-az2tf/scripts/azurerm_application_gateway.py", line 199, in azurerm_application_gateway
    fr.write('\t host_name = "' + bhn + '"\n')
TypeError: cannot concatenate 'str' and 'NoneType' objects
TypeError: cannot concatenate 'str' and 'NoneType' objects
Error in az2tf.py

**Comment by andyt530** [comment]
just submitted a 'quick fix' please give it a try - might need more work yet.

**Comment by MDavies-AA** [comment]
thanks,

Sorry about the awful formatting above.

Got me a bit further but it looks like it doesn't like one of the subnets being delegated for Azure Netapp Files.
#####

Error: expected delegation.0.service_delegation.0.name to be one of [Microsoft.Batch/batchAccounts Microsoft.ContainerInstance/containerGroups Microsoft.HardwareSecurityModules/dedicatedHSMs Microsoft.Logic/integrationServiceEnvironments Microsoft.Netapp/volumes Microsoft.ServiceFabricMesh/networks Microsoft.Sql/managedInstances Microsoft.Sql/servers Microsoft.Web/serverFarms], got Microsoft.NetApp/volumes

  on azurerm_subnet.infrastructure__azne-subn-itocore-netapp-1.tf line 1, in resource "azurerm_subnet" "infrastructure__azne-subn-itocore-netapp-1":
   1: resource azurerm_subnet infrastructure__azne-subn-itocore-netapp-1 {


Error Validating

**Comment by andyt530** [comment]
Ah - that one is actually a terraform bug - terraform is not recognising "Microsoft.NetApp/volumes" as a valid delegation - and it should do.  Could you submit an issue with them at https://github.com/terraform-providers/terraform-provider-azurerm-  I would do it but off on holiday in an hour !

**Comment by MDavies-AA** [comment]
No problem I'll raise it with them. Hope you have a great holiday!
