### ISSUE TITLE
Error in az2tf.py 

### ISSUE THREAD

**Issue by rjohnson318** [andyt530/py-az2tf#24]
Thanks for the tool!! I am new to terraform and was referred here. I am attempting to use this tool in the Azure Government sector specifically usdodeast and I ran into a python error. 
ENV details:
OS: CentOS 7.6

Package Versions:
azure-cli v2.0.71
Terraform v0.12.7
Python v2.7.5
export ARM_ENVIRONMENT=usgovernment

```
python2.7 ../../scripts/az2tf.py -s <subscriptionID> 2>&1 | tee -a import.log
Traceback (most recent call last):
  File "../../scripts/az2tf.py", line 4, in <module>
    import requests
ImportError: No module named requests
ImportError: No module named requests
Error in az2tf.py
```

**Comment by rjohnson318** [comment]
> Thanks for the tool!! I am new to terraform and was referred here. I am attempting to use this tool in the Azure Government sector specifically usdodeast and I ran into a python error.
> ENV details:
> OS: CentOS 7.6
> 
> Package Versions:
> azure-cli v2.0.71
> Terraform v0.12.7
> Python v2.7.5
> export ARM_ENVIRONMENT=usgovernment
> 
> ```
> python2.7 ../../scripts/az2tf.py -s <subscriptionID> 2>&1 | tee -a import.log
> Traceback (most recent call last):
>   File "../../scripts/az2tf.py", line 4, in <module>
>     import requests
> ImportError: No module named requests
> ImportError: No module named requests
> Error in az2tf.py
> ```

Ok fixed that error and other import errors no module named ..... with ```pip install requests```. Now getting :
```
python2.7 ../../scripts/az2tf.py -s <subscriptionID> 2>&1 | tee -a import.log
Get Access Token from CLI
Subscription: <subscriptionID>
Error getting subscription list
ErrorGettingSubscriptionList
Error getting subscription list
ErrorGettingSubscriptionList
Error in az2tf.py
```

**Comment by rjohnson318** [comment]
I tested the tool in the public cloud all is good but in the government cloud, I get the error getting subscription list errors. Somewhere in the code is missing where to find the gov subscriptions b/c it finds the public ones just fine.

**Comment by rjohnson318** [comment]
figured out that if I generate a token and use this command I can pull resources. I just don't know how to put that into the code in place of what is already there.

`curl -X GET --header "Authorization: Bearer $token" https://management.usgovcloudapi.net/subscriptions/<subscriptionID>/resources?api-version=2019-05-10`

**Comment by andyt530** [comment]
There would need to be a lot of changes to support Azure Gov. It's not on my priorities right now, not least as I don't have access.

If you want to have a go - you'd need to figure out the correct URL's and API versions for every REST api call that is made.
