### ISSUE TITLE
file name too long

### ISSUE THREAD

**Issue by brianott** [andyt530/py-az2tf#28]
IOError: [Errno 36] File name too long: u'azurerm_network_security_group.citrix-xd-0feb107a-80db-493a-8ea0-3da8bca85a47-kebbz__Citrix-Deny-All-a3pgu-0feb107a-80db-493a-8ea0-3da8bca85a47.tf'
IOError: [Errno 36] File name too long: u'azurerm_network_security_group.citrix-xd-0feb107a-80db-493a-8ea0-3da8bca85a47-kebbz__Citrix-Deny-All-a3pgu-0feb107a-80db-493a-8ea0-3da8bca85a47.tf'
Error in az2tf.py

Any reasonable way to bypass this? thank you.

**Comment by andyt530** [comment]
Can you post the debug output please:

./az2tf.py -s yoursub -d yes -v yes -r network_security_group 
maybe add -g citrix-xd-0feb107a-80db-493a-8ea0-3da8bca85a47-kebbz

if that's the name of the resource group ?

**Comment by brianott** [comment]
./az2tf.sh -s 7ae67ce1-a6f7-4d2d-a23f-1d59482a1989 -d yes -v yes -r network_security_group -g citrix-xd-0feb107a-80db-493a-8ea0-3da8bca85a47-kebbz
 
Subscription ID = 7ae67ce1-a6f7-4d2d-a23f-1d59482a1989
Azure Resource Group Filter = citrix-xd-0feb107a-80db-493a-8ea0-3da8bca85a47-kebbz
Terraform Resource Type Filter = network_security_group
Get Subscription Policies & RBAC = no
Extract Key Vault Secrets to .tf files (insecure) = no
Fast Forward = no
Validate Only = yes
Debug = no
 
rm: cannot remove '*network_security_group*.tf': No such file or directory
python2.7 ../../scripts/az2tf.py -s 7ae67ce1-a6f7-4d2d-a23f-1d59482a1989 -g citrix-xd-0feb107a-80db-493a-8ea0-3da8bca85a47-kebbz -r network_security_group -d yes 2>&1 | tee -a import.log
resource group=citrix-xd-0feb107a-80db-493a-8ea0-3da8bca85a47-kebbz
resource filter=network_security_group
Debug=True
Get Access Token from CLI
Subscription: 7ae67ce1-a6f7-4d2d-a23f-1d59482a1989
Found subscription 7ae67ce1-a6f7-4d2d-a23f-1d59482a1989 proceeding ...
Found Resource Groupcitrix-xd-0feb107a-80db-493a-8ea0-3da8bca85a47-kebbz

[redacted json]

Traceback (most recent call last):
  File "../../scripts/az2tf.py", line 297, in <module>
    azurerm_network_security_group.azurerm_network_security_group(crf,cde,crg,headers,requests,sub,json,az2tfmess)
  File "/home/bott/git/py-az2tf/scripts/azurerm_network_security_group.py", line 41, in azurerm_network_security_group
    fr=open(rfilename, 'w')
IOError: [Errno 36] File name too long: u'azurerm_network_security_group.citrix-xd-0feb107a-80db-493a-8ea0-3da8bca85a47-kebbz__Citrix-Deny-All-a3pgu-0feb107a-80db-493a-8ea0-3da8bca85a47.tf'
IOError: [Errno 36] File name too long: u'azurerm_network_security_group.citrix-xd-0feb107a-80db-493a-8ea0-3da8bca85a47-kebbz__Citrix-Deny-All-a3pgu-0feb107a-80db-493a-8ea0-3da8bca85a47.tf'

**Comment by brianott** [comment]
I think I will just skip this resource group since I don't care about it; but perhaps this is useful to report it to you anyway.

**Comment by andyt530** [comment]
ok thanks - are those resource group names and resource names machine generated? As they seem to contain GID/uuid's - unusual - and hence why the compound filename gets too long. I'd have to write something to detect long filenames and deal with it.

**Comment by brianott** [comment]
Yes, you are correct; part of a citrix auto deployed setup.

**Comment by andyt530** [comment]
Project archived with the release of the 2.0 azurerm providers
