### ISSUE TITLE
unable to run

### ISSUE THREAD

**Issue by coreydeli** [andyt530/py-az2tf#29]
running this from Windows 10 1903 using the Azure CLI I get the following error, verified Python 2.7 exists

```
bash: az: command not found

Subscription ID = Redacted
Azure Resource Group Filter =
Terraform Resource Type Filter =
Get Subscription Policies & RBAC = no
Extract Key Vault Secrets to .tf files (insecure) = no
Fast Forward = no
Validate Only = yes
Debug = no

python2.7 ../../scripts/az2tf.py -s SubScription>&1 | tee -a import.log
bash: python2.7: command not found
```

Unable to get around this issue.

**Comment by andyt530** [comment]
you may need to alias "python2.7" to python - assuming the "python" command is how you get to python 2.7 on your machine.  Note the "bash: az command not found" - that needs to be fixed as well before this tool has any chance of working.  (VirtualBox and a Linux VM maybe?)

**Comment by coreydeli** [comment]
checked in my powershell screen, typed in Python and it showed version 2.7.16 as the current version. So it looks like the alias is already set as is.

Ran the script in the linux subsystem (ubuntu) and recieved the following output:

```
Subscription ID = Redacted
Azure Resource Group Filter =
Terraform Resource Type Filter =
Get Subscription Policies & RBAC = no
Extract Key Vault Secrets to .tf files (insecure) = no
Fast Forward = no
Validate Only = yes
Debug = no

python2.7 ../../scripts/az2tf.py -s =Redaxted>&1 | tee -a import.log
Traceback (most recent call last):
  File "../../scripts/az2tf.py", line 4, in <module>
    import requests
ImportError: No module named requests
ImportError: No module named requests
Error in az2tf.py
```

**Comment by coreydeli** [comment]
Note that Terraform --version spits out 0.12.9

**Comment by andyt530** [comment]
ok that's a little better - Try:

pip install requests

and have another go.

**Comment by coreydeli** [comment]
Had to install Requests and Adal both it seems. It seems to be running right now though. I think my issue running wihtin PowerShell was that it was launching Git Bash and failing in that and not actually in PowerShell itself. I am going to remove GitBash and see if that works as well. I will report back when its done, may be worth adding a line or two to check for pip and Requests/Adal as well.

**Comment by coreydeli** [comment]
Looks like that worked! Thank you!
