### ISSUE TITLE
Output Errors creating .tf files

### ISSUE THREAD

**Issue by coreydeli** [andyt530/py-az2tf#30]
the module azurerm_storage_account does not include the argument "default_value = Allow/Deny" when a network restriction is set to an account Causes immediate validation errors.

Deprication warnings exist as well with the following errors:

Warning: "zone_type": [DEPRECATED] Use the `azurerm_private_dns_zone` resource instead.
Warning: "network_security_group_id": [DEPRECATED] Use the azurerm_subnet_network_security_group_association` resource instead.

Works wonerfully outside of that, thank you!

**Comment by andyt530** [comment]
Hi 
I can fix that if you post  the debug output please:

./az2tf.sh -s yoursub -v yes -d yes -r storage_account -g your_resource_group_name

You can blank out anything sensitive.

**Comment by coreydeli** [comment]
-d yes will not initiate a debug unfortunately. everything else is working though.

**Comment by andyt530** [comment]
The debug output comes out early - it may of scrolled past  ?

**Comment by andyt530** [comment]
please reopen - or new issue if this is still a problem
