### ISSUE TITLE
Error Invalid return character or leading space in header:Authorization

### ISSUE THREAD

**Issue by mmigala** [andyt530/py-az2tf#33]
Hello, 

I'm getting the error provided in the screen when running the script.

![image](https://user-images.githubusercontent.com/24477615/66923217-b35bb280-f028-11e9-967c-4d1014a2f845.png)

Regards

**Comment by andyt530** [comment]
pip install requests

and try again.

**Comment by mmigala** [comment]
I'm not sure why but at the end of bearer token '\r' was added. 

I removed it with:
`headers = {'Authorization': 'Bearer ' + bt.replace('\r',''), 'Content-Type': 'application/json'}`

and script started working

**Comment by andyt530** [comment]
Thanks - coded that in now.
