### ISSUE TITLE
Python cannot find "requests" module

### ISSUE THREAD

**Issue by sergejgoldstein** [andyt530/py-az2tf#35]
I downloaded the repo, unzipped to an empty directory, CDed to the directory that had the az2tf.sh script, and issued the following command:

./az2tf.sh -s mysubsciptionid -g mygroupdname -v yes

I got:
Subscription ID = myssubscriptionid
Azure Resource Group Filter = mygroupsname
Terraform Resource Type Filter = 
Get Subscription Policies & RBAC = no
Extract Key Vault Secrets to .tf files (insecure) = no
Fast Forward = no
Validate Only = yes
Debug = no
 
python2.7 ../../scripts/az2tf.py -s 3fde759f-01ac-48dd-b16b-885608b2be16 -g wase 2>&1 | tee -a import.log
Traceback (most recent call last):
  File "../../scripts/az2tf.py", line 4, in <module>
    import requests
ImportError: No module named requests
ImportError: No module named requests
Error in az2tf.py

**Comment by andyt530** [comment]
pip install requests

and try again

**Comment by jrgeorge40** [comment]
Still have the issue as well even after the pip install requests

Edit: It was using a newer version of Python for me. Once fixed, I got past this issue. Will post the next one I ran into.
