### ISSUE TITLE
Invalid escape sequence

### ISSUE THREAD

**Issue by jrgeorge40** [andyt530/py-az2tf#36]
I am getting the following error. It looks like it doesn't know how to properly treat backslashes in naming conventions.

Message:

Error: Invalid escape sequence

  on azurerm_virtual_network.daze2-network-rg__dAZE2-Dev-vnet.tf line 17, in resource "azurerm_virtual_network" "daze2-network-rg__dAZE2-Dev-vnet":
  17:    "AppTaxonomy"="ITIS\Infrastructure\Dev"

The symbol "I" is not a valid escape sequence selector.

**Comment by andyt530** [comment]
Looks like that's coming from Terraform itself isn't it ?

Could you post some extra lines before/after so I can see more context.

**Comment by jrgeorge40** [comment]
I think this is because the tags have a "\" in them and it is qualifying this as an escape character. so I think that this is an issue with implementation and something that Terraform is not able to handle.

**Comment by andyt530** [comment]
Closing as this is a Terraform issue rather than az2tf.
