### ISSUE TITLE
Error in az2tf.py Unicode for Policy info

### ISSUE THREAD

**Issue by jrgeorge40** [andyt530/py-az2tf#37]
Command run: ./az2tf.sh -s <SubscriptionId> -v yes -p yes 
Image of error:
![Annotation 2019-10-21 165657](https://user-images.githubusercontent.com/9645044/67246361-e2589680-f423-11e9-8427-a69265ba0f96.png)

**Comment by andyt530** [comment]
can you post the debug output for this please (include -d yes)

**Comment by jrgeorge40** [comment]
The error is in the description.
Expecting:
Resource Tags – Allows for logical organization of resources, consolidation of billing, supports maintenance cycles, and expedites incident response.
 Output:
"type": "Microsoft.Authorization/policySetDefinitions",
    "properties": {
        "displayName": "Resource Tagging Standard (Dev)",
        "description": "Resource Tags \u2013 Allows for logical organization of resources, consolidation of billing, supports maintenance cycles, and expedites incident response.\n",
        "parameters": {},
        "policyDefinitions": [

**Comment by andyt530** [comment]
Worth trying again - as the python3 version handles character encoding better than python2
