### ISSUE TITLE
Support for other Azure Clouds

### ISSUE THREAD

**Issue by mharrison365** [andyt530/py-az2tf#39]
Attempted to use this with Azure China, but received errors that it couldn't find the tenant or subscription specified. Dove into the code a bit, and looks like the API URL is hard-coded as https://management.azure.com/... in several places. Would probably be good to map this url value to an input parameter looking for "AzureCloud", "AzureChinaCloud", "AzureUSGovernment", or "AzureGermanCloud" - matching az cli.

**Comment by mharrison365** [comment]
I have forked this and added an additional argument for "cldurl", which allows the corresponding cloud API URL to be passed in. Currently testing and debugging...

**Comment by mharrison365** [comment]
Going to go ahead and initiate a pull request, however I do not have any presence in Azure US Gov or Azure Germany, so am not able to test these fully.

**Comment by andyt530** [comment]
merged in - thank you
