### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by guyEVO** [andyt530/py-az2tf#4]
Thanks for this great tool. I'm just starting to learn Terraform and have used this tool to create TF files for some resources already provisioned into our tenant by a previous employee. I'm trying to run it today on some PaaS applications, it could be that this error is related to an unsupported resource but I don't understand the python code enough yet to know! This is being run on the Terraform marketplace image, created today and AZ2TF was freshly cloned onto it.

python2.7 ../../scripts/az2tf.py -s <mySubID> 2>&1 | tee -a import.log
Get Access Token from CLI
Subscription: <mySubID>
Found subscription <mySubID> proceeding ...
# azurerm_resource_group 8
# azurerm_management_lock 2
Traceback (most recent call last):
  File "../../scripts/az2tf.py", line 277, in <module>
    azurerm_management_lock.azurerm_management_lock(crf,cde,crg,headers,requests,sub,json,az2tfmess)
  File "/home/stsadmin/py-az2tf/scripts/azurerm_management_lock.py", line 67, in azurerm_management_lock
    fr.write('\t notes = "'+ notes + '"\n')
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 74: ordinal not in range(128)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 74: ordinal not in range(128)
Error in az2tf.py

**Comment by andyt530** [comment]
Thanks for feedback - should be fixed now. Please let me know how you get on.

**Comment by guyEVO** [comment]
Thanks for the prompt fix Andy, all working now :)
