### ISSUE TITLE
Warning: "network_security_group_id": [DEPRECATED] Use the `azurerm_subnet_network_security_group_association` resource instead.

### ISSUE THREAD

**Issue by tazd007** [andyt530/py-az2tf#43]
Hi 
Are there any plans to adjust this I'm manually changing it for now but it would be great if the module would create these.
Thanks 
Tony

**Comment by andyt530** [comment]
azurerm_subnet_network_security_group_association resources are created within the azurerm_subnet.*.tf  files

References to network_security_group_id's have been removed

This should resolve your issue.
