### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by satheeshpanampilly** [andyt530/py-az2tf#46]
Hi,
Am getting an error when trying to execute az2tf.sh script to generate tto terraform files.
Pasting the error below. I have just used this command. " ./az2tf.sh -s <Subscription ID>".

ERROR BELOW:-

Traceback (most recent call last):
  File "../../scripts/az2tf.py", line 385, in <module>
    azurerm_virtual_machine_scale_set.azurerm_virtual_machine_scale_set(crf,cde,crg,headers,requests,sub,json,az2tfmess,cldurl)
  File "/usr/csuser/clouddrive/tf/az2tf/py-az2tf/scripts/azurerm_virtual_machine_scale_set.py", line 65, in azurerm_virtual_machine_scale_set
    osvhd = azr[i]["properties"]["virtualMachineProfile"]["osProfile"]["linuxConfiguration"]["ssh"]["publicKeys"][0]["keyData"]
IndexError: list index out of range
IndexError: list index out of range
Error in az2tf.py

Please check and revert. 
THanx

**Comment by andyt530** [comment]
please post the debug output 
./az2tf.sh -s xxxxxx -d yes -v yes

**Comment by satheeshpanampilly** [comment]
[import.log](https://github.com/andyt530/py-az2tf/files/4153923/import.log)
Hi,

Attached import logs created by the tool. Please check.
THanx

**Comment by andyt530** [comment]
Cool will post a fix in a few hours time.

**Comment by satheeshpanampilly** [comment]
Thanx a lot Andy for the response.

**Comment by andyt530** [comment]
posted fix

**Comment by satheeshpanampilly** [comment]
Thanx a lot Andy. That worked.

**Comment by satheeshpanampilly** [comment]
Hi Andy,

Actually got the same error for the environment or resource group which i tried yesterday which has loadbalancers, networks, vmscale sets etc.

**Comment by andyt530** [comment]
Same error ?
The line causing your original error has been deleted so that shouldn’t be possible. Does the place your running from need a git pull/clone

**Comment by satheeshpanampilly** [comment]
Yes the same error. I removed the old code and done a fresh git clone and then tried to execute and got into same error.

**Comment by satheeshpanampilly** [comment]
Error below.

Traceback (most recent call last):
  File "../../scripts/az2tf.py", line 385, in <module>
    azurerm_virtual_machine_scale_set.azurerm_virtual_machine_scale_set(crf,cde,crg,headers,requests,sub,json,az2tfmess,cldurl)
  File "/usr/csuser/clouddrive/tf/az2tf/py-az2tf/scripts/azurerm_virtual_machine_scale_set.py", line 129, in azurerm_virtual_machine_scale_set
    vmsshpath = azr[i]["properties"]["virtualMachineProfile"]["osProfile"]["linuxConfiguration"]["ssh"]["publicKeys"][0]["path"]
IndexError: list index out of range
IndexError: list index out of range
Error in az2tf.py

**Comment by andyt530** [comment]
Different line number !
Fix will be posted later today

**Comment by satheeshpanampilly** [comment]
OK Thanx

**Comment by andyt530** [comment]
fix posted

**Comment by satheeshpanampilly** [comment]
Thanx Andy. Will check and let you Know.

**Comment by andyt530** [comment]
going to assume this one is ok now - please reopen of further issues

**Comment by satheeshpanampilly** [comment]
Hello Andy,
Now problem comes during init. Pasting below error details.

Error: Invalid multi-line string

  on azurerm_network_security_group.tfnon__Tfnonpns.tf line 19, in resource "azurerm_network_security_group" "tfnon__Tfnonpns":
  19:
  21:

Quoted strings may not be split over multiple lines. To produce a multi-line
string, either use the \n escape to represent a newline character or use the
"heredoc" multi-line template syntax.


Error: Unterminated template string

  on azurerm_network_security_group.tfnon__Tfnonpns.tf line 19, in resource "azurerm_network_security_group" "tfnon__Tfnonpns":
  19:
  21:

No closing marker was found for the string.

Error: Invalid multi-line string
Error: Unterminated template string
Error with terraform init

**Comment by andyt530** [comment]
Please open as a new issue

Include the debug output & import.log
