### ISSUE TITLE
The argument "fqdns" was already set at fqdns = ["x.x.x.x"] 

### ISSUE THREAD

**Issue by nathan-clark** [andyt530/py-az2tf#48]
Awesome project -thanks

resource "azurerm_application_gateway"

backend_address_pool {
	 name = "be21"
	 fqdns = ["x.x.x.x"] 
	 fqdns = ["x.x.x.x"] 

Think this should be a list

**Comment by andyt530** [comment]
quick fix posted  - let me know if it works !

**Comment by andyt530** [comment]
reproduced here - fix posted
