### ISSUE TITLE
Note in resource "azurerm_management_lock"

### ISSUE THREAD

**Issue by nathan-clark** [andyt530/py-az2tf#49]
I have 

data "azurerm_subscription" "current" {}

resource "azurerm_management_lock" "subscription-level" {
...
  notes      = "Items can't be deleted in the "Group" Subscription"
}

which results in An argument definition must end with a newline.

**Comment by andyt530** [comment]
it's the quotes around the Group causing the problem - I've committed an attempt to fix it, please try again.

**Comment by nathan-clark** [comment]
Thanks I now get:

`Traceback (most recent call last):
  File "../../scripts/az2tf.py", line 385, in <module>
    azurerm_virtual_machine_scale_set.azurerm_virtual_machine_scale_set(crf,cde,crg,headers,requests,sub,json,az2tfmess,cldurl)
  File "/py-az2tf/scripts/azurerm_virtual_machine_scale_set.py", line 247, in azurerm_virtual_machine_scale_set
    ddname = datadisks["name"]
TypeError: list indices must be integers or slices, not str
TypeError: list indices must be integers or slices, not str
Error in az2tf.py`

**Comment by andyt530** [comment]
fix posted please give it another go

**Comment by nathan-clark** [comment]
Getting there ;)
`Traceback (most recent call last):
  File "../../scripts/az2tf.py", line 431, in <module>
    azurerm_function_app.azurerm_function_app(crf,cde,crg,headers,requests,sub,json,az2tfmess,cldurl)
  File "/py-az2tf/scripts/azurerm_function_app.py", line 143, in azurerm_function_app
    fr.write('\t version = "' + vers + '"\n')
UnboundLocalError: local variable 'vers' referenced before assignment
UnboundLocalError: local variable 'vers' referenced before assignment
Error in az2tf.py
`

**Comment by andyt530** [comment]
another fix posted :-)

**Comment by nathan-clark** [comment]
Thanks for your efforts Andy,

fqdns again.

Error: Invalid number literal

  on azurerm_application_gateway.grp.tf line 30, in resource "azurerm_application_gateway" "test__grp":
  30: 	 fqdns =  x.x.x.x

Failed to recognize the value of this number literal.


Error: Attribute redefined

  on azurerm_application_gateway.grp.tf line 31, in resource "azurerm_application_gateway" "test__grp":
  31: 	 fqdns =  x.x.x.x

The argument "fqdns" was already set at
azurerm_application_gateway.grp.tf:30,3-8. Each argument may be
set only once.

**Comment by andyt530** [comment]
will need the debug output on that one please

**Comment by andyt530** [comment]
reproduced your issue here - fix posted

**Comment by nathan-clark** [comment]
Sorry got bogged down in something else

```
[{'ipAddress': 'x.x.x.x'}, {'ipAddress': 'x.x.x.x'}]
Traceback (most recent call last):
  File "../../scripts/az2tf.py", line 361, in <module>
    azurerm_application_gateway.azurerm_application_gateway(crf,cde,crg,headers,requests,sub,json,az2tfmess,cldurl)
  File "/scripts/azurerm_application_gateway.py", line 205, in azurerm_application_gateway
    fr.write('\t path = "' + bhtpath + '"\n')
TypeError: can only concatenate str (not "NoneType") to str
TypeError: can only concatenate str (not "NoneType") to str
Error in az2tf.py
```

**Comment by andyt530** [comment]
More complicated to fix than I thought - another attempt posted - thanks for your patience with this.

**Comment by nathan-clark** [comment]
np u got nothing else todo on a Sunday ;)

```
Error: Error parsing /py-az2tf/generated/tf.8999dec3-0104-4a27-94ee-6588559729d1/azurerm_app_service_slot.bard-api-grp__bard-api-grp__staging.tf: At 5:25: Unknown token: 5:25 IDENT azurerm_resource_group.bard-api-grp.name

Error with terraform init

```
sorry not possible to upload debug
in that .tf file:

```
resource azurerm_app_service_slot bard-api-grp__bard-api-grp__test {
	 name = "test"
	...
	 resource_group_name = azurerm_resource_group.bard-api-grp.name
```

**Comment by andyt530** [comment]
Think that one is a case issue with the resource group name could you do:

$ cd generated/tf.8999dec3-0104-4a27-94ee-6588559729d1
$ terraform state list | grep resource_group

and post the output of whatever it says for the resource group "bard-api-grp" or "BARD-API-GRP" or what ever else it lists

Thanks

**Comment by andyt530** [comment]
Might also be worth clearing out (rm -rf tf.8999dec3-0104-4a27-94ee-6588559729d1) as - there shouldn't be any .tf files hanging around in there at the "terraform init" step.

**Comment by nathan-clark** [comment]
re-cloned, get same error on tf state list
Failed to load backend: Error loading backend config: Error parsing /py-az2tf/generated/tf.8999dec3-0104-4a27-94ee-6588559729d1/azurerm_app_service_slot.bard-api-grp__bard-api-grp__test.tf: 
At 5:25: Unknown token: 5:25 IDENT azurerm_resource_group.bard-api-grp.name

think this is the app service slot name?

in GUI it reads:
test (bard-api-grp/test)
App Service (Slot)
this is in RG: bard-api-grp

**Comment by andyt530** [comment]
ok - backed out some of the name de-referencing of "name" values in app slots  - simpler but not elegant. Lets see if that gets us past this issue in azurerm_app_service_slot

**Comment by nathan-clark** [comment]
it does, agw again.

resource azurerm_application_gateway nom-net-prod__nom-net-prod {
…
gateway_ip_configuration {
     name = "appGatewayIpConfig"
     subnet_id = azurerm_subnet.main-inf-grp__nom-net.id <---- Unknown token: IDENT 
}

**Comment by nathan-clark** [comment]
id is:

 "id": "[concat(parameters('virtualNetworks_main_inf_vnet_grp_externalid'), '/subnets/nom-net')]"

**Comment by andyt530** [comment]
Hi,

I'm going to need the output of ./az2tf.sh -s xxxxx -v yes -d yes 

To progress that one.

**Comment by nathan-clark** [comment]
no easy way to scrub output i'm afraid

**Comment by andyt530** [comment]
Ok - how about:

terraform state list | grep azurerm_subnet 
Look for the relevant subnet we're trying to reference in the gateway and paste that line here.

Then also  look at the "source of truth" for az2tf - login to 
https://resources.azure.com

select your subscription 
& resource group 
& providers
& Microsoft.Net
& applicationGateways
& your-gateway (nom-net-prod)

Look in there for the gatewayIPConfiguration block and 
 "subnet" :  {   within  and on the next line 
"id" : {

And paste the value of that id line here (you can remove the subscription id) - but I need to see the rest of it along with the terraform state list from above to see if they match and if not why not.

**Comment by andyt530** [comment]
do the terraform state list from the generated/tf.xxxxxxxxxxxxxxxx    directory

**Comment by andyt530** [comment]
Project archived with the release of the 2.0 azurerm providers
