### ISSUE TITLE
azurerm_virtual_network_gateway_connection issue

### ISSUE THREAD

**Issue by pbosle** [andyt530/py-az2tf#50]
Hi everyone

I do get the following error:

# azurerm_virtual_network_gateway_connection
4
Traceback (most recent call last):
  File "../../scripts/az2tf.py", line 367, in <module>
    azurerm_virtual_network_gateway_connection.azurerm_virtual_network_gateway_connection(crf,cde,crg,headers,requests,sub,json,az2tfmess,cldurl)
  File "/home/philippe/py-az2tf-master/scripts/azurerm_virtual_network_gateway_connection.py", line 104, in azurerm_virtual_network_gateway_connection
    fr.write('\t peer_virtual_network_gateway_id = azurerm_virtual_network_gateway.' + peerrg +'__' + peernam + '.id\n')
UnboundLocalError: local variable 'peerrg' referenced before assignment
UnboundLocalError: local variable 'peerrg' referenced before assignment
Error in az2tf.py

Cheers Philippe

**Comment by andyt530** [comment]
Hi Phiippe

Could you post the debug output - I should be able to fix it quickly then:

./az2tf.sh -s xxxxxxx   -v yes -d yes -g [resource group where the gateway is]

Thanks

**Comment by pbosle** [comment]
Hi Andy

Thanks for the fast reply. I have attached the output.

Cheers Philippe

[debug.log](https://github.com/andyt530/py-az2tf/files/4198536/debug.log)

**Comment by andyt530** [comment]
attempt at a fix posted

**Comment by pbosle** [comment]
Hi Andy

Thanks! It looks like the former issue is solved as I hit now at least another error (from terraform?):

_Warning: "location": [DEPRECATED] location is no longer used

  on azurerm_virtual_machine_extension.dga-central-rg__vm-central-linux-1__AzureNetworkWatcherExtension.tf line 2, in resource "azurerm_virtual_machine_extension" "dga-central-rg__vm-central-linux-1__AzureNetworkWatcherExtension":
   2: resource azurerm_virtual_machine_extension dga-central-rg__vm-central-linux-1__AzureNetworkWatcherExtension{

(and 6 more similar warnings elsewhere)


Warning: "resource_group_name": [DEPRECATED] This field has been deprecated and is no longer used - will be removed in 2.0 of the Azure Provider

  on azurerm_virtual_machine_extension.dga-central-rg__vm-central-linux-1__AzureNetworkWatcherExtension.tf line 2, in resource "azurerm_virtual_machine_extension" "dga-central-rg__vm-central-linux-1__AzureNetworkWatcherExtension":
   2: resource azurerm_virtual_machine_extension dga-central-rg__vm-central-linux-1__AzureNetworkWatcherExtension{

(and 6 more similar warnings elsewhere)


Warning: "virtual_machine_name": [DEPRECATED] This field has been deprecated in favor of `virtual_machine_id` - will be removed in 2.0 of the Azure Provider

  on azurerm_virtual_machine_extension.dga-central-rg__vm-central-linux-1__AzureNetworkWatcherExtension.tf line 2, in resource "azurerm_virtual_machine_extension" "dga-central-rg__vm-central-linux-1__AzureNetworkWatcherExtension":
   2: resource azurerm_virtual_machine_extension dga-central-rg__vm-central-linux-1__AzureNetworkWatcherExtension{

(and 6 more similar warnings elsewhere)


Error: Reference to undeclared resource

  on azurerm_virtual_network_gateway_connection.dga-central-rg__conn-s2s-central-to-west.tf line 10, in resource "azurerm_virtual_network_gateway_connection" "dga-central-rg__conn-s2s-central-to-west":
  10:    peer_virtual_network_gateway_id = azurerm_virtual_network_gateway.dga-west-rg__vng-west-dmz-vpn.id

A managed resource "azurerm_virtual_network_gateway"
"dga-west-rg__vng-west-dmz-vpn" has not been declared in the root module._

Error Validating




Here is a new debug.log:
[debug.log](https://github.com/andyt530/py-az2tf/files/4203145/debug.log)


For some reason the last output did not go into the debug.log:
A managed resource "azurerm_virtual_network_gateway"
"dga-west-rg__vng-west-dmz-vpn" has not been declared in the root module._

Error Validating

cheers Philippe

**Comment by andyt530** [comment]
Hi - fix posted for error.
I'll work through those warnings in the next few days - they are a new thing !

**Comment by pbosle** [comment]
Hi Andy

Muchas gracias!

Philippe

**Comment by andyt530** [comment]
Warnings should have gone now
Closing - reopen if further issues
