### ISSUE TITLE
Invalid multi-line string error

### ISSUE THREAD

**Issue by satheeshpanampilly** [andyt530/py-az2tf#56]
Hi

GOt Invalid multi-line string error when executing az2tf script for a subscription. Please find attached import log for the same executed with debug output.
[import.log](https://github.com/andyt530/py-az2tf/files/4251095/import.log)

Thanx

**Comment by andyt530** [comment]
Odd - can't see the NSG TfNondmzNSG in the debug output 

Also can you post the contents of the file  network_security_group.Non__TfNondmzNSG.tf

**Comment by satheeshpanampilly** [comment]
Really Odd. Can see the file or contents named network_security_group.Non__TfNondmzNSG.tf.

**Comment by satheeshpanampilly** [comment]
Attached file azurerm_network_security_group.tfnonproduction__TfnonproddmzNSG.tf which has the above resource in it.
[azurerm_network_security_group.tfnonproduction__TfnonproddmzNSG.txt](https://github.com/andyt530/py-az2tf/files/4254085/azurerm_network_security_group.tfnonproduction__TfnonproddmzNSG.txt)

**Comment by andyt530** [comment]
Project archived with the release of the 2.0 azurerm providers
